opencti:
  url: 'http://docker-opencti-1:8080'
  token: '1f144533-583a-4bb5-863c-451bbdc09d49'

connector:
  id: '8db780d8-45e0-4e0f-9c75-de17de42fe3f'
  type: 'EXTERNAL_IMPORT'
  name: 'MITRE Datasets'
  scope: 'tool,report,malware,identity,campaign,intrusion-set,attack-pattern,course-of-action,x-mitre-data-source,x-mitre-data-component,x-mitre-matrix,x-mitre-tactic,x-mitre-collection'
  run_and_terminate: false
  log_level: 'info'
  expose_metrics: False

mitre:
  remove_statement_marking: true
  interval: 7 # In days
